version: '3'
services:
  node-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "1447:8989"  # Change the ports if you adjusted you're setup
    environment:
      - NODE_ENV=production
    networks:
      - mydu-server-custom_vpcbr #change this to the network the mydu stack is running



networks:
  mydu-server-custom_vpcbr: #change this to the network the mydu stack is running
    external: true